// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Carts
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public bool IsCheckedOut { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<CartItems> CartItems { get; set; } = new List<CartItems>();

    public virtual Users User { get; set; }
}