// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Categories
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string? ImageUrl { get; set; }

    public virtual ICollection<Products> Product { get; set; } = new List<Products>();
}