// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repos.Models;

public partial class HotWaterGasDBContext : DbContext
{
    public HotWaterGasDBContext()
    {
    }

    public HotWaterGasDBContext(DbContextOptions<HotWaterGasDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CartItems> CartItems { get; set; }

    public virtual DbSet<Carts> Carts { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<Discounts> Discounts { get; set; }

    public virtual DbSet<EmailVerifications> EmailVerifications { get; set; }

    public virtual DbSet<OrderItems> OrderItems { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<PasswordResets> PasswordResets { get; set; }

    public virtual DbSet<PaymentTransactions> PaymentTransactions { get; set; }

    public virtual DbSet<ProductImages> ProductImages { get; set; }

    public virtual DbSet<ProductMetadatas> ProductMetadatas { get; set; }

    public virtual DbSet<ProductSystemRequirements> ProductSystemRequirements { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<ProductCategories> ProductCategories { get; set; }

    public virtual DbSet<ProductTags> ProductTags { get; set; }

    public virtual DbSet<Reviews> Reviews { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<SteamKeys> SteamKeys { get; set; }

    public virtual DbSet<Tags> Tags { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<RefreshTokens> RefreshTokens { get; set; }

    public virtual DbSet<WishlistItems> WishlistItems { get; set; }

    public virtual DbSet<Wishlists> Wishlists { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Configuration is handled via dependency injection in Program.cs.
        // For design-time tools (EF Core CLI), use HotWaterGasDBContextFactory.
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CartItems>(entity =>
        {
            entity.HasIndex(e => new { e.CartId, e.ProductId }, "IX_CartItems_CartId_ProductId").IsUnique();

            entity.HasIndex(e => e.ProductId, "IX_CartItems_ProductId");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems).HasForeignKey(d => d.CartId);

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Carts>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_Carts_UserId")
                .IsUnique()
                .HasFilter("\"IsCheckedOut\" = false");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.User).WithOne(p => p.Carts).HasForeignKey<Carts>(d => d.UserId);
        });

        modelBuilder.Entity<Categories>(entity =>
        {
            entity.HasIndex(e => e.Slug, "IX_Categories_Slug").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Slug).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
        });

        modelBuilder.Entity<Discounts>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Percentage).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<EmailVerifications>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_EmailVerifications_UserId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CodeHash).IsRequired();

            entity.HasOne(d => d.User).WithOne(p => p.EmailVerifications).HasForeignKey<EmailVerifications>(d => d.UserId);
        });

        modelBuilder.Entity<OrderItems>(entity =>
        {
            entity.HasIndex(e => e.OrderId, "IX_OrderItems_OrderId");

            entity.HasIndex(e => e.ProductId, "IX_OrderItems_ProductId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.LineTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems).HasForeignKey(d => d.OrderId);

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasIndex(e => e.DiscountId, "IX_Orders_DiscountId");

            entity.HasIndex(e => e.UserId, "IX_Orders_UserId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FinalTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Discount).WithMany(p => p.Orders).HasForeignKey(d => d.DiscountId);

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PasswordResets>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_PasswordResets_Email");

            entity.HasIndex(e => e.UserId, "IX_PasswordResets_UserId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CodeHash).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Email).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResets)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<PaymentTransactions>(entity =>
        {
            entity.HasIndex(e => e.OrderId, "IX_PaymentTransactions_OrderId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CheckoutUrl)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.ProviderOrderCode).IsRequired();

            entity.HasOne(d => d.Order).WithOne(p => p.PaymentTransactions).HasForeignKey<PaymentTransactions>(d => d.OrderId);
        });

        modelBuilder.Entity<ProductImages>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_ProductImages_ProductId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ImageUrl).IsRequired();

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages).HasForeignKey(d => d.ProductId);
        });

        modelBuilder.Entity<ProductMetadatas>(entity =>
        {
            entity.HasKey(e => e.ProductId);

            entity.Property(e => e.ProductId).ValueGeneratedNever();
            entity.Property(e => e.Developer).IsRequired();
            entity.Property(e => e.Platform).IsRequired();
            entity.Property(e => e.Publisher).IsRequired();

            entity.HasOne(d => d.Product).WithOne(p => p.ProductMetadatas).HasForeignKey<ProductMetadatas>(d => d.ProductId);
        });

        modelBuilder.Entity<ProductSystemRequirements>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_ProductSystemRequirements_ProductId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.MinimumGraphics).HasMaxLength(300);
            entity.Property(e => e.MinimumMemory).HasMaxLength(100);
            entity.Property(e => e.MinimumNotes).HasMaxLength(500);
            entity.Property(e => e.MinimumOs)
                .HasMaxLength(300)
                .HasColumnName("MinimumOS");
            entity.Property(e => e.MinimumProcessor).HasMaxLength(300);
            entity.Property(e => e.MinimumStorage).HasMaxLength(100);
            entity.Property(e => e.RecommendedGraphics).HasMaxLength(300);
            entity.Property(e => e.RecommendedMemory).HasMaxLength(100);
            entity.Property(e => e.RecommendedNotes).HasMaxLength(500);
            entity.Property(e => e.RecommendedOs)
                .HasMaxLength(300)
                .HasColumnName("RecommendedOS");
            entity.Property(e => e.RecommendedProcessor).HasMaxLength(300);
            entity.Property(e => e.RecommendedStorage).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithOne(p => p.ProductSystemRequirements).HasForeignKey<ProductSystemRequirements>(d => d.ProductId);
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasIndex(e => e.DiscountId, "IX_Products_DiscountId");

            entity.HasIndex(e => e.Name, "IX_Products_Name");

            entity.HasIndex(e => e.Price, "IX_Products_Price");

            entity.HasIndex(e => e.Slug, "IX_Products_Slug").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ShortDescription)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasDefaultValue("");

            entity.Property(e => e.IsFeatured)
                .IsRequired()
                .HasDefaultValue(false);

            entity.HasOne(d => d.Discount).WithMany(p => p.Products)
                .HasForeignKey(d => d.DiscountId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasMany(d => d.Category).WithMany(p => p.Product)
                .UsingEntity<ProductCategories>(
                    j => j.HasOne(pc => pc.Category).WithMany().HasForeignKey(pc => pc.CategoryId),
                    j => j.HasOne(pc => pc.Product).WithMany().HasForeignKey(pc => pc.ProductId),
                    j => j.HasKey(pc => new { pc.ProductId, pc.CategoryId }));

            entity.HasMany(d => d.Tag).WithMany(p => p.Product)
                .UsingEntity<ProductTags>(
                    j => j.HasOne(pt => pt.Tag).WithMany().HasForeignKey(pt => pt.TagId),
                    j => j.HasOne(pt => pt.Product).WithMany().HasForeignKey(pt => pt.ProductId),
                    j => j.HasKey(pt => new { pt.ProductId, pt.TagId }));
        });

        modelBuilder.Entity<Reviews>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_Reviews_ProductId");

            entity.HasIndex(e => new { e.UserId, e.ProductId }, "IX_Reviews_UserId_ProductId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Comment).IsRequired();
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Product).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.Reviews).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<SteamKeys>(entity =>
        {
            entity.HasIndex(e => e.OrderId, "IX_SteamKeys_OrderId");

            entity.HasIndex(e => new { e.ProductId, e.Status }, "IX_SteamKeys_ProductId_Status");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.KeyValue).IsRequired();
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            entity.HasOne(d => d.Order).WithMany(p => p.SteamKeys).HasForeignKey(d => d.OrderId);

            entity.HasOne(d => d.Product).WithMany(p => p.SteamKeys)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Tags>(entity =>
        {
            entity.HasIndex(e => e.Slug, "IX_Tags_Slug").IsUnique();
            entity.HasIndex(e => e.Name, "IX_Tags_Name").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).IsRequired().HasMaxLength(450);
            entity.Property(e => e.Slug).IsRequired().HasMaxLength(120);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_Users_Email").IsUnique();

            entity.HasIndex(e => e.RoleId, "IX_Users_RoleId");

            entity.HasIndex(e => e.GoogleId, "IX_Users_GoogleId");

            entity.HasIndex(e => e.RefreshToken, "IX_Users_RefreshToken");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.PasswordHash).IsRequired(false);
            entity.Property(e => e.DisplayName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.IsSuspended).IsRequired().HasDefaultValue(false);
            entity.Property(e => e.RefreshToken).HasMaxLength(512);
            entity.Property(e => e.RefreshTokenExpiresAt).HasColumnType("timestamp with time zone");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WishlistItems>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_WishlistItems_ProductId");

            entity.HasIndex(e => new { e.WishlistId, e.ProductId }, "IX_WishlistItems_WishlistId_ProductId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Product).WithMany(p => p.WishlistItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Wishlist).WithMany(p => p.WishlistItems).HasForeignKey(d => d.WishlistId);
        });

        modelBuilder.Entity<Wishlists>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_Wishlists_UserId").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.User).WithOne(p => p.Wishlists).HasForeignKey<Wishlists>(d => d.UserId);
        });

        modelBuilder.Entity<RefreshTokens>(entity =>
        {
            entity.HasIndex(e => e.TokenHash)
                .IsUnique()
                .HasDatabaseName("IX_RefreshTokens_TokenHash");

            entity.HasIndex(e => e.UserId)
                .HasDatabaseName("IX_RefreshTokens_UserId");

            entity.HasIndex(e => e.TokenFamilyId)
                .HasDatabaseName("IX_RefreshTokens_TokenFamilyId");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(128);

            entity.Property(e => e.CreatedByIp).HasMaxLength(45);

            entity.Property(e => e.RevokedByIp).HasMaxLength(45);

            entity.Property(e => e.UserAgent).HasMaxLength(512);

            entity.Property(e => e.DeviceInfo).HasMaxLength(256);

            entity.HasOne(d => d.User)
                .WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.ParentToken)
                .WithMany()
                .HasForeignKey(d => d.ParentTokenId)
                .OnDelete(DeleteBehavior.NoAction);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}