// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class OrderItems
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public Guid ProductId { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal LineTotal { get; set; }

    public int Quantity { get; set; }

    public Guid? SourceCartItemId { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Products Product { get; set; }
}