// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Orders
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid? CartId { get; set; }

    public decimal Subtotal { get; set; }

    public int Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public decimal DiscountAmount { get; set; }

    public Guid? DiscountId { get; set; }

    public decimal FinalTotal { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? FulfilledAt { get; set; }

    public DateTime? FulfillmentEmailClaimedAt { get; set; }

    public DateTime? FulfillmentEmailSentAt { get; set; }

    public string FulfillmentLastError { get; set; }

    public virtual Discounts Discount { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    public virtual PaymentTransactions PaymentTransactions { get; set; }

    public virtual ICollection<SteamKeys> SteamKeys { get; set; } = new List<SteamKeys>();

    public virtual Users User { get; set; }
}