// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class PasswordResets
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string Email { get; set; }

    public string CodeHash { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public DateTime? ConsumedAt { get; set; }

    public int AttemptCount { get; set; }

    public DateTime? LastSentAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ResetTokenHash { get; set; }

    public DateTime? ResetTokenExpiresAt { get; set; }

    public virtual Users User { get; set; }
}