// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class PaymentTransactions
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public string ProviderOrderCode { get; set; }

    public int Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CheckoutUrl { get; set; }

    public int Provider { get; set; }

    public string ProviderTransactionId { get; set; }

    public string QrCodeUrl { get; set; }

    public string RawRequestPayload { get; set; }

    public string RawResponsePayload { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Orders Order { get; set; }
}