// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Products
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public Guid? DiscountId { get; set; }

    public bool IsDeleted { get; set; }

    public int Stock { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ShortDescription { get; set; }

    public string Slug { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CartItems> CartItems { get; set; } = new List<CartItems>();

    public virtual Discounts Discount { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    public virtual ICollection<ProductImages> ProductImages { get; set; } = new List<ProductImages>();

    public virtual ProductMetadatas ProductMetadatas { get; set; }

    public virtual ProductSystemRequirements ProductSystemRequirements { get; set; }

    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();

    public virtual ICollection<SteamKeys> SteamKeys { get; set; } = new List<SteamKeys>();

    public virtual ICollection<WishlistItems> WishlistItems { get; set; } = new List<WishlistItems>();

    public virtual ICollection<Categories> Category { get; set; } = new List<Categories>();

    public virtual ICollection<Tags> Tag { get; set; } = new List<Tags>();
}