// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class ProductMetadatas
{
    public Guid ProductId { get; set; }

    public string Publisher { get; set; }

    public string Developer { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public string Platform { get; set; }

    public virtual Products Product { get; set; }
}