// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class ProductSystemRequirements
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string MinimumOs { get; set; }

    public string MinimumProcessor { get; set; }

    public string MinimumMemory { get; set; }

    public string MinimumGraphics { get; set; }

    public string MinimumStorage { get; set; }

    public string MinimumNotes { get; set; }

    public string RecommendedOs { get; set; }

    public string RecommendedProcessor { get; set; }

    public string RecommendedMemory { get; set; }

    public string RecommendedGraphics { get; set; }

    public string RecommendedStorage { get; set; }

    public string RecommendedNotes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Products Product { get; set; }
}