// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class ProductImages
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string ImageUrl { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsPrimary { get; set; }

    public virtual Products Product { get; set; }
}