// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class SteamKeys
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string KeyValue { get; set; }

    public Guid? OrderId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? InvalidatedAt { get; set; }

    public int Status { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Products Product { get; set; }
}