// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Repos.Models;

public partial class Tags
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Products> Product { get; set; } = new List<Products>();
}
