// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Users
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string? PasswordHash { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid RoleId { get; set; }

    public bool IsEmailVerified { get; set; }

    public string DisplayName { get; set; } = string.Empty;

    public string? GoogleId { get; set; }

    public string? AvatarUrl { get; set; }

    public virtual Carts Carts { get; set; }

    public virtual EmailVerifications EmailVerifications { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<PasswordResets> PasswordResets { get; set; } = new List<PasswordResets>();

    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();

    public virtual ICollection<RefreshTokens> RefreshTokens { get; set; } = new List<RefreshTokens>();

    public virtual Roles Role { get; set; }

    public virtual Wishlists Wishlists { get; set; }
}