// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class WishlistItems
{
    public Guid Id { get; set; }

    public Guid WishlistId { get; set; }

    public Guid ProductId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Products Product { get; set; }

    public virtual Wishlists Wishlist { get; set; }
}