// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repos.Models;

public partial class Wishlists
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public virtual Users User { get; set; }

    public virtual ICollection<WishlistItems> WishlistItems { get; set; } = new List<WishlistItems>();
}